version: "3.6"

services: # Under service we are going to DESCRIBE the containers

    mariadb: # network name that you can use to refer to that dontainer within the network that was created for them
        container_name:     mymariadb
        image:              mariadb:latest
        volumes:
                          - /home/ubuntu/environment/mydata/mariadb:/var/lib/mysql
        environment:
                          - MARIADB_ROOT_PASSWORD=password
                          - MARIADB_DATABASE=database
                          - MARIADB_USER=user
                          - MARIADB_PASSWORD=password
    
    wordpress:
        container_name:     mywordpress
        image:              wordpress:latest
        volumes:
                          - /home/ubuntu/environment/mydata/wordpress:/var/www/html
        ports:
                          - 8080:80 
        environment:
            WORDPRESS_DB_NAME:      database
            WORDPRESS_DB_USER:      user
            WORDPRESS_DB_PASSWORD:  password
            WORDPRESS_DB_HOST:      mariadb:3306
